components:
  splitter:
    type: src.ingest.components.recursive_splitter.RecursiveDocumentSplitter
    init_parameters:
      chunk_size: ${CHUNK_SPLIT_LENGTH}
      chunk_overlap: ${CHUNK_SPLIT_OVERLAP}
  embedder:
    type: src.ingest.components.bge_m3_embedder.BGE_M3DocumentEmbedder
    init_parameters:
      batch_size: 64
  perm_enricher:
    type: src.ingest.components.perm_enricher.PermissionMetadataEnricher
    init_parameters: {}
  writer:
    type: src.ingest.components.milvus_writer.MilvusDocumentStoreWriter
    init_parameters:
      collection_name: rag_documents
      milvus_host: ${MILVUS_HOST}
      milvus_port: ${MILVUS_PORT}
connections:
- sender: splitter.documents
  receiver: embedder.documents
- sender: embedder.documents
  receiver: perm_enricher.documents
- sender: perm_enricher.documents
  receiver: writer.documents
